name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Set appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v4
        id: setSHAs

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint for Affected Projects
        run: pnpm nx affected:lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Set appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v4
        id: setSHAs

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests for Affected Projects
        run: pnpm nx affected:test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Set appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v4
        id: setSHAs

      - name: Install Dependencies
        run: pnpm install

      - name: Build Affected Projects
        run: pnpm nx affected:build

  deploy:
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Set appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v4
        id: setSHAs

      - name: Install Dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::909221929648:role/GitHub
          role-duration-seconds: 14390
          aws-region: eu-west-2

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/develop'
        run: pnpm deploy:demo

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: pnpm deploy:prod
